modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="komugimod"
version="0.2.2-alpha"
displayName="Komugi Mod"
description='''
"Komugi" means wheat in Japanese.
'''
